# 一. 包的简介

1.  大型数据集处理\
2.  数据以行为单位存储,占用的内存空间更少,更快的数据操作速度,提供了一些特殊的语法和函数\
3.  'as.data.table()' 可将数据框、列表、矩阵等转化为 data.table\

<!--加载包 -->

library(data.table)

<!-- 查看前5行数据 -->

head(mtcars, 5)

```{=html}
<!--                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
    Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
    Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
    Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
    Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
    Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
    -->
```

<!-- 转化为 data.table -->

mtcars_table = as.data.table(mtcars)

head(mtcars_table, 5)

```{=html}
<!-- 查看前5行数据 
         mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
       <num> <num> <num> <num> <num> <num> <num> <num> <num> <num> <num>
    1:  21.0     6   160   110  3.90 2.620 16.46     0     1     4     4
    2:  21.0     6   160   110  3.90 2.875 17.02     0     1     4     4
    3:  22.8     4   108    93  3.85 2.320 18.61     1     1     4     1
    4:  21.4     6   258   110  3.08 3.215 19.44     1     0     3     1
    5:  18.7     8   360   175  3.15 3.440 17.02     0     0     3     2
    -->
```

# 二. 数据的导入和导出问题

1.  'fread()'\
2.  CSV、TSV、txt、zip、gz……\
3.  'fwrite()'\

<!--加载包等过程同上 -->

<!--添加到zy4文件夹中 -->

fwrite(mtcars_table, "zy4/mtcars_table.csv")

<!--从文件中写入-->

mtcars_table1 \<- fread("zy4/mtcars_table.csv")

mtcars_table1

```{=html}
<!--     
     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
    <num> <int> <num> <int> <num> <num> <num> <int> <int> <int> <int>
 1:  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
 ………………………………………………………………………………………………………………………………………………………………………………（省略）
32:  21.4     4 121.0   109  4.11 2.780 18.60     1     1     4     2
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb -->
```

# 三. 基本语法

1.i ：行选择（Row Selection）;j：列操作（Column Operation）;by：分组（Group By）\
2.i :用来指定行的条件,索引，增删……（筛选，排序，合并）\
j :用来指定对列的操作，可以是选择列、计算新列、聚合……\
by :用来指定分组变量,表示按照某一列或多列进行分组后，再对每个组执行 j 中的操作\
3.i（筛选行）→ by（分组）→ j（操作列）\
<!--筛选出 气缸数为 6-->

mtcars_table1[cyl == 6]

```{=html}
     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
   <num> <int> <num> <int> <num> <num> <num> <int> <int> <int> <int>
1:  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
2:  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
3:  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
4:  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
5:  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
6:  17.8     6 167.6   123  3.92 3.440 18.90     1     0     4     4
7:  19.7     6 145.0   175  3.62 2.770 15.50     0     1     5     6
```

<!--选取 前 5 行-->

mtcars_table1[1:5]

```{=html}
    mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
   <num> <int> <num> <int> <num> <num> <num> <int> <int> <int> <int>
1:  21.0     6   160   110  3.90 2.620 16.46     0     1     4     4
2:  21.0     6   160   110  3.90 2.875 17.02     0     1     4     4
3:  22.8     4   108    93  3.85 2.320 18.61     1     1     4     1
4:  21.4     6   258   110  3.08 3.215 19.44     1     0     3     1
5:  18.7     8   360   175  3.15 3.440 17.02     0     0     3     2
```

<!--选择 mpg 和 cyl 两列-->

mtcars_table1[,.(mpg,cyl)]

```{=html}
      mpg   cyl
    <num> <int>
 1:  21.0     6
…………………………………………………………（省略）
32:  21.4     4
      mpg   cyl
```

<!--计算 平均hp 和 最大disp-->

mtcars_table1[, .(mean_hp = mean(hp), max_disp = max(disp))]

```{=html}
    mean_hp max_disp
      <num>    <num>
1: 146.6875      472
```

<!--按mpg分组，算平均hp，最大disp-->

mtcars_table1[, .(mean_hp = mean(hp), max_disp = max(disp)),by = mpg]

```{=html}
      mpg mean_hp max_disp
    <num>   <num>    <num>
 1:  21.0   110.0    160.0
 2:  22.8    94.0    140.8
 3:  21.4   109.5    258.0
 4:  18.7   175.0    360.0
 5:  18.1   105.0    225.0
 6:  14.3   245.0    360.0
 7:  24.4    62.0    146.7
 8:  19.2   149.0    400.0
 9:  17.8   123.0    167.6
10:  16.4   180.0    275.8
11:  17.3   180.0    275.8
12:  15.2   165.0    304.0
13:  10.4   210.0    472.0
14:  14.7   230.0    440.0
15:  32.4    66.0     78.7
16:  30.4    82.5     95.1
17:  33.9    65.0     71.1
18:  21.5    97.0    120.1
19:  15.5   150.0    318.0
20:  13.3   245.0    350.0
21:  27.3    66.0     79.0
22:  26.0    91.0    120.3
23:  15.8   264.0    351.0
24:  19.7   175.0    145.0
25:  15.0   335.0    301.0
      mpg mean_hp max_disp
```

<!--cyl大于6，按mpg分组，算平均hp，最大disp-->

mtcars_table1[cyl \> 6, .(mean_hp = mean(hp), max_disp = max(disp)),by = mpg]

```{=html}
      mpg mean_hp max_disp
    <num>   <num>    <num>
 1:  18.7     175    360.0
 2:  14.3     245    360.0
 3:  16.4     180    275.8
 4:  17.3     180    275.8
 5:  15.2     165    304.0
 6:  10.4     210    472.0
 7:  14.7     230    440.0
 8:  15.5     150    318.0
 9:  13.3     245    350.0
10:  19.2     175    400.0
11:  15.8     264    351.0
12:  15.0     335    301.0
```

#四、变量引⽤

1.在 j 表达式中直接使用列名\
<!--cyl+mpg数值加起来-->

mtcars_table1[,.(mpg,cyl,mc=mpg+cyl)]

```{=html}
      mpg   cyl    mc
    <num> <int> <num>
 1:  21.0     6  27.0
 2:  21.0     6  27.0
 3:  22.8     4  26.8
 4:  21.4     6  27.4
 5:  18.7     8  26.7
 6:  18.1     6  24.1
 7:  14.3     8  22.3
 8:  24.4     4  28.4
 9:  22.8     4  26.8
10:  19.2     6  25.2
11:  17.8     6  23.8
12:  16.4     8  24.4
13:  17.3     8  25.3
14:  15.2     8  23.2
15:  10.4     8  18.4
16:  10.4     8  18.4
17:  14.7     8  22.7
18:  32.4     4  36.4
19:  30.4     4  34.4
20:  33.9     4  37.9
21:  21.5     4  25.5
22:  15.5     8  23.5
23:  15.2     8  23.2
24:  13.3     8  21.3
25:  19.2     8  27.2
26:  27.3     4  31.3
27:  26.0     4  30.0
28:  30.4     4  34.4
29:  15.8     8  23.8
30:  19.7     6  25.7
31:  15.0     8  23.0
32:  21.4     4  25.4
      mpg   cyl    mc
```

#五、 数据筛选I

1.mtcars_table1[i] (i 为逻辑 / 整数 / 字符向量,逻辑矩阵，list)\
mtcars_table1为表名，i：变量名 \>、=、\< 某值\
2.mtcars_table1[, j] (j 为 .(列名), 字符 / 整数向量)\
…………………………………………………，j：'1:5'索引也可以。'\< \>'时返回'true'or'false'\
3.使用 \$ 操作符，使用 [[ ]]，使用 [ ,j ] (j为列名，索引也行)\
4.大部分可以

<!--table的行列筛选在 三.基本语法 已展示。下面展示frame的行列筛选-->

frame = as.data.frame(mtcars_table)

frame[,"cyl"]

<!-- [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4-->

<!--添加列-->

frame \$ mc = frame \$ cyl + frame\$mpg

frame[,'mc']

```{=html}
<!--[1] 27.0 27.0 26.8 27.4 26.7 24.1 22.3 28.4 26.8 25.2 23.8 24.4 25.3 23.2 18.4 18.4 22.7 36.4 34.4 37.9
[21] 25.5 23.5 23.2 21.3 27.2 31.3 30.0 34.4 23.8 25.7 23.0 25.4-->
```

#六、数据筛选II

1.使用‘.()’

mtcars_table1[,.(mpg)]

```{=html}
      mpg
    <num>
 1:  21.0
 2:  21.0
 3:  22.8
 4:  21.4
 5:  18.7
 6:  18.1
 7:  14.3
 8:  24.4
 9:  22.8
10:  19.2
11:  17.8
12:  16.4
13:  17.3
14:  15.2
15:  10.4
16:  10.4
17:  14.7
18:  32.4
19:  30.4
20:  33.9
21:  21.5
22:  15.5
23:  15.2
24:  13.3
25:  19.2
26:  27.3
27:  26.0
28:  30.4
29:  15.8
30:  19.7
31:  15.0
32:  21.4
      mpg
```

2.使用'列名' '\$' '[[]]'

mtcars_table1[,mpg]

mtcars_table1\$mpg

mtcars_table1[['mpg']]

```{=html}
<!--结果都为
[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9
[21] 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7 15.0 21.4 -->
```

#七、排序

1.用 order(var1, var2, ...,decreasing=c(false,true,...))\
2.通过 decreasing 参数或负号控制升降序\
3.仅 i 部分（主动排序）和 by 部分（分组自动排序）支持直接排序，j 部分不支持\
4.可以

<!-- 先mpg升序，再cyl降序  -->

mtcars_table1[order(mpg,-cyl)]

```{=html}
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
    <num> <int> <num> <int> <num> <num> <num> <int> <int> <int> <int>
 1:  10.4     8 472.0   205  2.93 5.250 17.98     0     0     3     4
 2:  10.4     8 460.0   215  3.00 5.424 17.82     0     0     3     4
 3:  13.3     8 350.0   245  3.73 3.840 15.41     0     0     3     4
 4:  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
 5:  14.7     8 440.0   230  3.23 5.345 17.42     0     0     3     4
 6:  15.0     8 301.0   335  3.54 3.570 14.60     0     1     5     8
 7:  15.2     8 275.8   180  3.07 3.780 18.00     0     0     3     3
 8:  15.2     8 304.0   150  3.15 3.435 17.30     0     0     3     2
 9:  15.5     8 318.0   150  2.76 3.520 16.87     0     0     3     2
10:  15.8     8 351.0   264  4.22 3.170 14.50     0     1     5     4
11:  16.4     8 275.8   180  3.07 4.070 17.40     0     0     3     3
12:  17.3     8 275.8   180  3.07 3.730 17.60     0     0     3     3
13:  17.8     6 167.6   123  3.92 3.440 18.90     1     0     4     4
14:  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
15:  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
16:  19.2     8 400.0   175  3.08 3.845 17.05     0     0     3     2
17:  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
18:  19.7     6 145.0   175  3.62 2.770 15.50     0     1     5     6
19:  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
20:  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
21:  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
22:  21.4     4 121.0   109  4.11 2.780 18.60     1     1     4     2
23:  21.5     4 120.1    97  3.70 2.465 20.01     1     0     3     1
24:  22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
25:  22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
26:  24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
27:  26.0     4 120.3    91  4.43 2.140 16.70     0     1     5     2
28:  27.3     4  79.0    66  4.08 1.935 18.90     1     1     4     1
29:  30.4     4  75.7    52  4.93 1.615 18.52     1     1     4     2
30:  30.4     4  95.1   113  3.77 1.513 16.90     1     1     5     2
31:  32.4     4  78.7    66  4.08 2.200 19.47     1     1     4     1
32:  33.9     4  71.1    65  4.22 1.835 19.90     1     1     4     1
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
```

<!-- 先筛选.再mpg升序，cyl降序  -->

mtcars_table1[cyl \> 6][order(mpg,-cyl)]

```{=html}
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
    <num> <int> <num> <int> <num> <num> <num> <int> <int> <int> <int>
 1:  10.4     8 472.0   205  2.93 5.250 17.98     0     0     3     4
 2:  10.4     8 460.0   215  3.00 5.424 17.82     0     0     3     4
 3:  13.3     8 350.0   245  3.73 3.840 15.41     0     0     3     4
 4:  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
 5:  14.7     8 440.0   230  3.23 5.345 17.42     0     0     3     4
 6:  15.0     8 301.0   335  3.54 3.570 14.60     0     1     5     8
 7:  15.2     8 275.8   180  3.07 3.780 18.00     0     0     3     3
 8:  15.2     8 304.0   150  3.15 3.435 17.30     0     0     3     2
 9:  15.5     8 318.0   150  2.76 3.520 16.87     0     0     3     2
10:  15.8     8 351.0   264  4.22 3.170 14.50     0     1     5     4
11:  16.4     8 275.8   180  3.07 4.070 17.40     0     0     3     3
12:  17.3     8 275.8   180  3.07 3.730 17.60     0     0     3     3
13:  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
14:  19.2     8 400.0   175  3.08 3.845 17.05     0     0     3     2
```

#八、添加或更改列数据

1.不用函数，使用'：='\

mtcars_table1[,a:=mpg/cyl]

mtcars_table1[,c('b','c','d'):=.(mpg/cyl,disp-cyl,hp+drat)]

mtcars_table1

```{=html}
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb        a        b     c      d
    <num> <int> <num> <int> <num> <num> <num> <int> <int> <int> <int>    <num>    <num> <num>  <num>
 1:  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4 3.500000 3.500000 154.0 113.90
…………………………………………………………………………………………………………………………………………………………（省略）
32:  21.4     4 121.0   109  4.11 2.780 18.60     1     1     4     2 5.350000 5.350000 117.0 113.11
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb        a        b     c      d
```

#九、分组I

1.按指定变量拆分数据，组内独立操作，合并结果。相当于整个数据框分成了m个数据框，数据操作是分别在每个数据框上进行，汇总是得到 m 个结果\
2.keyby 会排序结果并创建键，使得更快地访问子集\
3.mtcars_table1[, .(sum_col1=sum(col1), sum_col2=sum(col2)……), by = .(var1, var2……)]，支持同时对多列求和。\
<!--按cyl分3组，再按vs不同分5组，再将组内数据求和-->

mtcars_table1[, .(sum_mpg=sum(mpg), sum_disp=sum(disp)), by = .(cyl, vs)]

```{=html}
     cyl    vs sum_mpg sum_disp
   <int> <int>   <num>   <num>
1:     6     0    61.7   465.0
2:     4     1   267.3  1036.2
3:     6     1    76.5   818.2
4:     8     0   211.4  4943.4
5:     4     0    26.0   120.3
```

#十、分组II

mtcars_table1[, .(sum_mpg=sum(mpg), sum_disp=sum(disp)), by = .(cyl, vs,am == 1)]

```{=html}
     cyl    vs     am sum_mpg sum_disp
   <int> <int> <lgcl>   <num>    <num>
1:     6     0   TRUE    61.7    465.0
2:     4     1   TRUE   198.6    628.6
3:     6     1  FALSE    76.5    818.2
4:     8     0  FALSE   180.6   4291.4
5:     4     1  FALSE    68.7    407.6
6:     4     0   TRUE    26.0    120.3
7:     8     0   TRUE    30.8    652.0
```

#十一、特殊函数I

1.‘.SD ’是 data.table 中的一个特殊变量，它代表 Subset of Data（数据子集）\
当不使用 by 进行分组时，.SD 就代表整个 data.table\
当使用 by 进行分组时，.SD 代表当前分组的数据子集\
2."data.table" "data.frame"\
3."data.table" "data.frame"

q = mtcars_table1[,.SD,by=cyl]

w = mtcars_table1[,.SD]

class(q)

class(w)

```{=html}
[1] "data.table" "data.frame"
[1] "data.table" "data.frame"
```

十二、特殊函数II

1..N 是 data.table 中的一个特殊变量，它代表 当前分组（或整个数据集）的行数。\
当不使用 by 进行分组时，.N 表示整个 data.table 的总行数。\
当使用 by 进行分组时，.N 表示每个分组的行数\
2.不分组时，.N 返回一个整数向量。\
3.分组时，.N 返回一个 data.table，包含分组变量和对应的行数\

mtcars_table1[,.N,by=cyl]

mtcars_table1[,.N]

```{=html}
     cyl     N
   <int> <int>
1:     6     7
2:     4    11
3:     8    14
> mtcars_table1[,.N]
[1] 32                
```

#十三、特殊函数III

1.将多个 data.table 的操作步骤通过方括号 []连续连接起来\
'dt[第一步操作][第二步操作][第三步操作]'\
2.用于需要执行多步数据处理的场景(操作步骤按顺序从左到右执行)\

mtcars_table1[vs==1 & am==1][,.(mpg_aver=mean(mpg),cyl_aver=mean(cyl))]

```{=html}
   mpg_aver cyl_aver
      <num>    <num>
1: 28.37143        4
```

#十四、join操作（横向合并）

1.方式一：使用 [ ] 操作符 (data.table 特有)\
dt1[dt2, on = .(var1, var2)] (在 dt1 和 dt2 之间，使用 var1 和 var2 这两列作为匹配的键)\
方式二：使用 merge() 函数 (与 base R 兼容)\
merge(dt1, dt2, by = c("var1", "var2")) (指定连接键)\

2.区别：[] 性能更好，可以即时计算\
merge 与 base R、dplyr 等兼容，主要进行数据合并，计算在合并后进行\
#十五、 bind操作（竖向合并）

1.rbind()

mtcars_table2 = mtcars_table1[,.SD+1]

rbind(mtcars_table1,mtcars_table2)

```{=html}
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
    <num> <num> <num> <num> <num> <num> <num> <num> <num> <num> <num>
 1:  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
 2:  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
 3:  22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
 4:  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
 5:  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
 6:  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
 7:  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
 8:  24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
 9:  22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
10:  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
11:  17.8     6 167.6   123  3.92 3.440 18.90     1     0     4     4
12:  16.4     8 275.8   180  3.07 4.070 17.40     0     0     3     3
13:  17.3     8 275.8   180  3.07 3.730 17.60     0     0     3     3
14:  15.2     8 275.8   180  3.07 3.780 18.00     0     0     3     3
15:  10.4     8 472.0   205  2.93 5.250 17.98     0     0     3     4
16:  10.4     8 460.0   215  3.00 5.424 17.82     0     0     3     4
………………………………………………………………………………………………………………………………………………………………………………………………（省略）
48:  11.4     9 461.0   216  4.00 6.424 18.82     1     1     4     5
49:  15.7     9 441.0   231  4.23 6.345 18.42     1     1     4     5
50:  33.4     5  79.7    67  5.08 3.200 20.47     2     2     5     2
51:  31.4     5  76.7    53  5.93 2.615 19.52     2     2     5     3
52:  34.9     5  72.1    66  5.22 2.835 20.90     2     2     5     2
53:  22.5     5 121.1    98  4.70 3.465 21.01     2     1     4     2
54:  16.5     9 319.0   151  3.76 4.520 17.87     1     1     4     3
55:  16.2     9 305.0   151  4.15 4.435 18.30     1     1     4     3
56:  14.3     9 351.0   246  4.73 4.840 16.41     1     1     4     5
57:  20.2     9 401.0   176  4.08 4.845 18.05     1     1     4     3
58:  28.3     5  80.0    67  5.08 2.935 19.90     2     2     5     2
59:  27.0     5 121.3    92  5.43 3.140 17.70     1     2     6     3
60:  31.4     5  96.1   114  4.77 2.513 17.90     2     2     6     3
61:  16.8     9 352.0   265  5.22 4.170 15.50     1     2     6     5
62:  20.7     7 146.0   176  4.62 3.770 16.50     1     2     6     7
63:  16.0     9 302.0   336  4.54 4.570 15.60     1     2     6     9
64:  22.4     5 122.0   110  5.11 3.780 19.60     2     2     5     3
      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
```

#十六、 melt与cast操作

melt()：宽格式 → 长格式\
id.vars（ID 列）、measure.vars（待融化列）、variable.name（变量列名）、value.name（值列名）\

dcast()：长格式 → 宽格式（或聚合格式）\
formula（ID 列～变量列）、value.var（值列名）、fun.aggregate（聚合函数，可选）\

<!--添加ID列-->

mtcars_table1[,name:=1:32]

<!--转写为长格式-->

mtcars_long = melt(data=mtcars_table1,id.vars="name",measure.vars=1:11,variable.name="va",value.name = "value")

mtcars_long

```{=html}
      name     va value
     <int> <fctr> <num>
  1:     1    mpg  21.0
  2:     2    mpg  21.0
  3:     3    mpg  22.8
  4:     4    mpg  21.4
  5:     5    mpg  18.7
 ---                   
348:    28   carb   2.0
349:    29   carb   4.0
350:    30   carb   6.0
351:    31   carb   8.0
352:    32   carb   2.0
```

<!--转写为宽格式-->

mtcars_width = dcast(data=mtcars_long,formula =name \~ va,value.var="value")

mtcars_width

```{=html}
Key: <name>
     name   mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
    <int> <num> <num> <num> <num> <num> <num> <num> <num> <num> <num> <num>
 1:     1  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
 2:     2  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
 3:     3  22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
 4:     4  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
 5:     5  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
 6:     6  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
 7:     7  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
 8:     8  24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
 9:     9  22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
10:    10  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
11:    11  17.8     6 167.6   123  3.92 3.440 18.90     1     0     4     4
12:    12  16.4     8 275.8   180  3.07 4.070 17.40     0     0     3     3
13:    13  17.3     8 275.8   180  3.07 3.730 17.60     0     0     3     3
14:    14  15.2     8 275.8   180  3.07 3.780 18.00     0     0     3     3
15:    15  10.4     8 472.0   205  2.93 5.250 17.98     0     0     3     4
16:    16  10.4     8 460.0   215  3.00 5.424 17.82     0     0     3     4
17:    17  14.7     8 440.0   230  3.23 5.345 17.42     0     0     3     4
18:    18  32.4     4  78.7    66  4.08 2.200 19.47     1     1     4     1
19:    19  30.4     4  75.7    52  4.93 1.615 18.52     1     1     4     2
20:    20  33.9     4  71.1    65  4.22 1.835 19.90     1     1     4     1
21:    21  21.5     4 120.1    97  3.70 2.465 20.01     1     0     3     1
22:    22  15.5     8 318.0   150  2.76 3.520 16.87     0     0     3     2
23:    23  15.2     8 304.0   150  3.15 3.435 17.30     0     0     3     2
24:    24  13.3     8 350.0   245  3.73 3.840 15.41     0     0     3     4
25:    25  19.2     8 400.0   175  3.08 3.845 17.05     0     0     3     2
26:    26  27.3     4  79.0    66  4.08 1.935 18.90     1     1     4     1
27:    27  26.0     4 120.3    91  4.43 2.140 16.70     0     1     5     2
28:    28  30.4     4  95.1   113  3.77 1.513 16.90     1     1     5     2
29:    29  15.8     8 351.0   264  4.22 3.170 14.50     0     1     5     4
30:    30  19.7     6 145.0   175  3.62 2.770 15.50     0     1     5     6
31:    31  15.0     8 301.0   335  3.54 3.570 14.60     0     1     5     8
32:    32  21.4     4 121.0   109  4.11 2.780 18.60     1     1     4     2
     name   mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
```
